#lang racket
( define (roll-die) ( random 1 7 ) )

( define (roll-for-1)
   ( define roll ( roll-die ) )
   ( display roll )
   ( display " " )
   ( if (= roll 1)
        ( display "" )
        ( roll-for-1 )
        )
   )

( define ( roll-for-11 )
   ( roll-for-1 )
   ( define deciding-roll (roll-die) )
   ( display deciding-roll )
   ( display " " )
   ( if ( = deciding-roll 1)
        ( display "" )
        ( roll-for-11 )
        )
   )

( define ( roll-for-odd )
   ( define roll ( roll-die ) )
   ( display roll )
   ( display " " )
   ( if ( = ( modulo roll 2) 1 )
        ( display "")
        ( roll-for-odd )
        )
   )

( define ( roll-for-odd-even )
   ( roll-for-odd )
   ( define roll (roll-die) )
   ( display roll )
   ( display " " )
   ( if ( = ( modulo roll 2 ) 0)
        ( display "")
        ( roll-for-odd-even )
        )
   )

( define ( roll-for-odd-even-odd )
   ( roll-for-odd-even )
   ( define roll (roll-die) )
   ( display roll )
   ( display " " )
   ( if ( = ( modulo roll 2 ) 1)
        ( display "")
        ( roll-for-odd-even-odd )
        )
   )

( define (display-tuple num1 num2)
   ( display "(" )
   ( display num1 )
   ( display "," )
   ( display num2 )
   ( display ")" )
   ( display " " )
   )

( define ( roll-two-dice-for-a-lucky-pair )
   ( define roll1 ( roll-die ) )
   ( define roll2 ( roll-die ) )
   ( display-tuple roll1 roll2 )
   ( cond
      ( ( = ( + roll1 roll2) 7 )
        ( display "" )
        )

      ( ( = ( + roll1 roll2) 11 )
        ( display "" )
        )

      ( ( = roll1 roll2 )
        ( display "" )
        )
      ( else ( roll-two-dice-for-a-lucky-pair ) )
      )
   )

